export const AUTH_ROUTE_PATH = '/auth'
export const CHATS_ROUTE_PATH = '/chats'
export const PROFILE_ROUTE_PATH = '/profile'
export const CHAT_ROUTE_PATH = '/chats/:id'
export const CHAT_POOL_PATH = '/chatPool'